trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- script: dotnet restore
  displayName: dotnet restore

- script: dotnet build
  displayName: dotnet build

- script: dotnet publish
  displayName: dotnet publish


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'