trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: dotnet restore
  displayName: dotnet restore

- script: dotnet build
  displayName: dotnet build

- script: dotnet publish 
  displayName: dotnet publish



- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\ExcellenceQuest.API\bin\Release\net8.0\publish'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureFileCopy@6
  inputs:
    SourcePath: '$(Build.SourcesDirectory)\ExcellenceQuest.API\bin\Release\net8.0\publish'
    azureSubscription: 'Free Trial(46f9ef38-22ea-47f1-91c9-c2ebcf8d74eb)'
    Destination: 'AzureVMs'
    storage: 'storageeeeeeeeee1211'
    resourceGroup: 'WINDOWSVM_GROUP'
    vmsAdminUserName: 'windowsvm'
    vmsAdminPassword: 'Bharathi@123'
    TargetPath: 'c:\inetpub\wwwroot'
    

