trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish' 
    outputPath: 'publish' 

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'publish' 
    ArtifactName: 'drop'
    publishLocation: 'Container'